src/systems/boards/Stat Display.j

Changes the warning from at 20 of a stat remaining to 25. Energy changed to prevent panicking at 21; others for consistency.

Update Stat Display.j

---

.vscode/tasks.json
compile.ps1

Script compile.ps1 now accepts arbitrary number of arguments rather than limiting user to single arg.
Improved script description, fixed spelling errors.
Note:Although '--scriptonly' is provided by default, specifying additional one will bring no harm, jasshelper will just ignore it.

Remove single arg restriction from compile script.

---

jass/lib/GameMode.zn

Added "-noelimination" and "-noel" to disable elimination mode and allow spirit wards again.

Added -noel mode to undo elimination mode.

---

wurst/systems/classes/mage/hypnotist/Jealousy.wurst

Sleep invulnerability + jealousy caused a crash. Fixed with invulnerability check.
Also updates target position constantly instead of thinking target is around the initial cast point.

FIX - Jealousy crash

---

jass/trolls/Upgrade.j

https://github.com/island-troll-tribes/island-troll-tribes/issues/106
Instead of getting stats hardcoded into subclasses you inherit your previous STR, AGI, and INT. This system avoids punishing overleveling and probably helps in the future too.
Also previously subbing from normal sub (14 all stats) to supersub (13 all stats) reduced your stats by 1.

Subbing changed to copy previous attributes

---

wurst/systems/spawns/ResourceSpawning.wurst

https://images-ext-2.discordapp.net/external/tdssOSfrdzraj1rvME9YdK0W0rbXGNfmYlELEJ-FQH4/%3Fwidth%3D721%26height%3D684/https/images-ext-1.discordapp.net/external/lpPp0dutn7Wk33QMLiya7JO9aP_wPnUSrioacdSDVjg/https/i.gyazo.com/thumb/1200/52790b5b770caca552e5e40cb2cb9a2b-jpg.jpg?width=720&height=684
In this image you see the old resource densities. My new values have been calculated in such a manner that these values will now be perfectly balanced on every island, and no matter where you walk around the likelihood of encountering resources per distance walked should be the same.

Balanced resource spawn weights

---

wurst/systems/units/hostiles/Hostile.wurst

The global wasnt accounted for in meat drop calculations

Fixed bug that prevented modes from affecting food gain, e.g. -lavish and -famine

---

wurst/systems/spells/priest/ReplenishHealth.wurst

https://github.com/island-troll-tribes/island-troll-tribes/issues/243
Replenish health simply used to detect order ID of immolation and unimmolation and activate based on that. Gatherer salve recipe dummy abilities had the same ID which lead to gatherer being able to have permanent replenish health effect on. The code also looked like it would not work at all for Master Healer and Sage

Fixed Replenish Health

---

wurst/systems/spells/gatherer/TeleGathering.wurst

Further improves telegather sorting by saving the last sorting positions used for the target campfire. Therefore the items dont get mixed up when another telegather is cast on the same fire.

Added caching for telegather sorting across casts

---

wurst.build
wurst/_items/Blowgun.wurst

Small fix to blowgun loading so the item doesnt swap slots with the ammunition if trying to load a full blowgun

Fixed blowgun item bounce on load

---

wurst/_items/Blowgun.wurst

Now that the itemcount system changes item names to for example, "Thistles (x3)" the blowgun was showing this twice such as "Thistles (x3) x3". Now the blowgun no longer adds a suffix of its own when listing ammo contained.

Blowgun ammo contents tooltip suffix removed

---

wurst/__legacy__/lib/CheatPack.jurst
wurst/systems/commands/Commands.wurst

Awar triggered me with a movement speed conversation, so I add to check it out ingame, realized -ms doesn't work very well in -dev mode.
I think this would be better :

Updated -ms command, now give ms of the selected unit

---

wurst/systems/commands/Commands.wurst
wurst/systems/commands/SpawningTestHelpers.wurst
wurst/systems/spawns/HostileNetBehavior.wurst

From what I saw, creep behavior seems to issue an move order back to initial position after ~6 seconds.
Made small bunch of code which will abort the move order when the unit's being targeted by ensnare ability.
Also added a "-hostile" command to give selected unit to PLAYER_NEUTRAL_AGGRESSIVE

Ensnared hostile will now abort the move order

---

wurst/__legacy__/crafting/Transmute.jurst
wurst/objects/items.wurst
wurst/objects/units/Merchants.wurst

$changelog: Removed Smoke House and Storage Hut from game.
$changelog: Replaced Storage Hut in first boat with Workshop.
$changelog: Replaced Smoke House in second boat with Magic.
$changelog: Changed Workshop price to 8 gold.

Removed Storage Hut/Smoke House from the game. Changed Workshop price.

---

wurst/extensions/PlayerExtensions.wurst
wurst/lib/commands/Alliances.wurst
wurst/lib/commands/ModifySelected.wurst
wurst/objects/abilities/MoveCorpses.wurst

$changelog: Added hotkey support for switching between grabbing and dropping corpses.
$changelog: Added lockout period when automatically switching between grabbing and dropping corpses.
This also addresses a bug with the `owner` toolkit command where the wrong argument was being parsed and adds toolkit commands for modifying alliance settings.

Improved UX for moving corpses.

---

wurst/lib/OrderStringFactory_config.wurst
wurst/lib/Toolkit.wurst
wurst/objects/abilities/TrollUpgradeSpell.wurst

$changelog: Fixed bug where corpses could not be grabbed for some classes.
For some reason, banning additional order IDs will cause the map to break. The order string factory currently only reaches `rainofchaos`, which comes before any of the other order IDs we would like to ban. Because of this, we can avoid banning them for now but it also means that banning them should have no effect.
Despite this, adding the commented code will cause the ability object output to still have all the same order IDs, but the button position for some channel abilities to be incorrect. These incorrect button positions all use `(0, 0)`, causing the map to crash.
This problem may go away if all order IDs use the factory. Some channel abilities current have their generated orders overridden by hard-coded …

Added additional orders to the banlist.

---

wurst/objects/units/TrollBuildings.wurst

This is no longer needed as of patch 1.32

Reverted UI hack. (#437)

---

wurst/objects/items/Raw.wurst

It said "restore 150 mana" because it's based off mana potion and the extended tooltip wasn't modified.

Corrected healing potion tooltip.

---

.gitignore
wurst/objects/abilities/MoveCorpses.wurst

$changelog: Changed hotkey for switching between abilities for moving corpses.
The previous hotkey V had two problems:
1. While no abilities used hotkey V innately, this conflicted with the hotkey for Sleep Outside when using the grid layout option built into Warcraft III as a whole.
2. The previous hotkey did not work when SHIFT was held down. Standard hotkeys have no such limitation, so this could confuse users. The addition of a metakey makes it clearer that the user must be precise.

Changed hotkey for switching between abilities for moving corpses.

---

wurst/lib/commands/Maphack.wurst

$changelog : fixed bug where the map start off as explored
I guess that creating the fog modifier reveal the area, I don't know why, but this is just a quickfix.

Explored map quickfix

---

wurst/__legacy__/crafting/Transmute.jurst
wurst/assets/LocalAssets.wurst
wurst/lib/OrderStringFactory_config.wurst
wurst/objects/abilities/scout/Reveal.wurst
wurst/objects/items/LivingClay.wurst
wurst/objects/units/DummyUnits.wurst
wurst/objects/units/Merchants.wurst
wurst/systems/commands/SpawningTestHelpers.wurst
wurst/systems/crafting/QuickMakeSpell.wurst
wurst/systems/crafting/QuickMakeToolTips.wurst
wurst/systems/crafting/WitchDoctorHutQuickMake.wurst
wurst/systems/crafting/WorkshopQuickMake.wurst
wurst/systems/entities/buildings/Workshop.wurst
wurst/systems/spawns/BushSpawns.wurst

$changelog: Reduced daytime sight radius of Living Clay to the nighttime value.
$changelog: Removed Scout Bush from the game.
$changelog: Added aura that will indicate when units are being watched by a ward. 
$changelog: Removed sell price for Living Clay.
$changelog: Moved Living Clay recipe to the Workshop.
$changelog: Changed Living Clay recipe to use Magic instead of Mana Crystal.

Nerfed Living Clay.

---

wurst/objects/abilities/gatherer/Radars.wurst
wurst/objects/abilities/mage/unsub/ReduceFood.wurst
wurst/objects/abilities/priest/sage/LightGateNew.wurst
wurst/objects/abilities/priest/unsub/AntiMagic.wurst
wurst/objects/abilities/priest/unsub/HealingWave.wurst
wurst/objects/abilities/priest/unsub/MixSpells.wurst
wurst/objects/abilities/priest/unsub/RangedHeal.wurst
wurst/objects/abilities/thief/contortionist/NewSmokeStream.wurst
wurst/objects/abilities/thief/escapeArtist/Jump.wurst
wurst/systems/crafting/QuickMakeSpell.wurst

Using generated orders causes problem when the target type is mismatched to the generated order. For example, generating `farsight` on a quickmake spell will break the original `farsight` for point orders, such as in the Far Sight spell.
The standard library must be adjusted to account for this and this change will have to wait until then.

Revert "Updated channel abilities to use generated orders. (#494)"

---

wurst/systems/crafting/QuickMakeSpell.wurst

Removing these quickmakes reduces the number of orders strings the factory has to generate, enough to not reach `raisedead` which problems being banned.

Removed some quickmakes temporarily.

---

wurst/systems/modes/GameModeInit.wurst
wurst/systems/modes/TameableFawn.wurst
wurst/systems/modes/TeamGoldSharing.wurst
wurst/systems/modes/TribeOwnsBuildings.wurst

Following the issue #519, I re-ordered the mode displayed a bit to put the most important/used (my POV) on the top, also removed some unused/testing mode from the board.
Removed -noel because it was unintuitive, typing -el again will disable it.
Removed -old-elementalist from the board, because I think we've gone past testing new elementalist and I don't see any much reason for playing old elementalist.
[Before](https://camo.githubusercontent.com/ac166fde4f0719e3a92270896a80367e606dd1ac/68747470733a2f2f692e6779617a6f2e636f6d2f35613962643538316263336231393831376162313134626566616138623838342e706e67)
[After](https://i.gyazo.com/d162b872ef5742f53250f5055d815093.jpg)

Reordered modes display.

---

scripts/release.py

#536 changed the UI to use upkeep for information regarding healing reduction. This used to hold the version so that all screenshots would indicate the version, but that usage wasn't as valuable.

Removed outdated version display.

---

wurst/objects/items/LivingClay.wurst

$changelog: Changed visual effect of Paranoia aura for Living Clay to an overhead eye, similar to Magic Sentry.
$changelog: Changed ward destruction so that only heroes can explode Living Clay.
Added the magic sentry buff on trolls spotted by ward, the buff still stay 2-3 seconds after ward being destroyed, it is the aura behavior.
Suggesting to change ward destruction targetsAllowed to only ground heroes.
It is very frustrating to have your wards getting randomly destroyed by elks, it was ok before because we had "free" ward & clay explosion, but now we need to use materials to create them.

Improved Living Clay behavior.

---

wurst.build
wurst/lib/Transformation.wurst
wurst/objects/abilities/TrollUpgrade.wurst
wurst/objects/abilities/beastMaster/Pets/Pets.wurst
wurst/objects/abilities/beastMaster/Shapeshift.wurst
wurst/systems/commands/Skins.wurst
wurst/systems/core/Experience.wurst
wurst/utils/LastOrder_config.wurst

Transforming a unit can sometimes disconnect it from the internal engine that handles the `instant` order, which is used for abilities like Raise Dead that target a single corpse. This order is responsible for choosing a nearby corpse and translating the immediate order into into a targeted order.
For unknown reasons, transforming a unit using the inverse Bear Form ability occasionally breaks Raise Dead but not Cannibalize. Furthermore, casting Cannibalize will actually correct the disconnect and allow Raise Dead to work again. This is leveraged by allowing specified transformations to include an after effect that simulates issuing a Cannibalize order in order to fix this disconnect for units that may need to cast Raise Dead or similar abilities in the future.

Updated transformation library to handle instant order bugs.

---

wurst/lib/Transformation.wurst
wurst/objects/abilities/MoveCorpses.wurst

This doesn't fix any existing abilities at the time of this PR. This work is being done so that the pet updates can use an ability based on Raise Dead.

Fixed corpse moving system blocking autocast orders incorrectly.

---

wurst/systems/crafting/QuickMakeSpell.wurst

-Mud hut kit would trigger panic.
-Forge & Omnitower would trigger each other, there was a typo on forge orderId

Fixed conflicting order IDs for quickmake abilities.

---

wurst/objects/abilities/priest/booster/TrollBattleCall.wurst

When I rewrote this spell, I put the wrong model as a target art, put back the old one, more visible this way.

Changed the model for the booster troll battle call target art

---

wurst/assets/LocalObjectIDs.wurst
wurst/objects/abilities/mage/hypnotist/Anger.wurst

$changelog: Added an Exhaust debuff that is applied to the target of Anger after its effect ends, which reduces its attack speed by 50% and movement speed by 25% for 4 seconds.
Some people reported anger being too strong, I think this debuff makes sense, can tweak the numbers.

Added a debuff on Anger's target after the effect ends.

---

wurst/objects/abilities/scout/WardArea.wurst
wurst/objects/items/LivingClay.wurst

$changelog: Added area of effect indicator for abilities that place wards which matches the sight radius of the ward.
A quality of life suggestion.

Added area of effect indicator for wards to match sight radius.

---

wurst/objects/abilities/beastMaster/Pets/PetMovement.wurst
wurst/objects/abilities/beastMaster/Pets/PetMovementAbility.wurst

$changelog: Fixed issue where some players would crash at start.
Tracking the mouse position for controlling pets was causing desyncs. So the ability to control your pet by hitting a key has been removed as there seems to be no other way to do it at the moment.

Fixed desync issue with pet movement.

---

wurst/objects/abilities/mage/unsub/SpiritPrison.wurst

$changelog: Fixed bugs where Spirit Prison could hit multiple targets and be used multiple times without cooldown.
Spirit had a conflicting baseOrderId with quick make mixing pot.
I don't really understand how am I supposed to use the order banning, but I figured "blink" was banned due to thief teleport, so I set spirit prison baseOrderId to "blink" for now.

Fixed bugs associated with Spirit Prison.

---

wurst/systems/entities/bosses/DiscoDuck.wurst
wurst/systems/entities/bosses/Mammoth.wurst
wurst/systems/entities/modules/Hostile.wurst

$changelog: Mammoth & Disco Duck death now display a message to all player.
People reported that Bosses death were too important to be left unknown for the the opponent team, they requested this change.

Added a message displayed on mammoth & disco duck death

---

wurst/objects/abilities/mage/hypnotist/DreamEater.wurst

$changelog: Fixed bug where dream eater would go on cooldown when casted on non-hypnotized target

Reverted dream eater condition check so it prevent spellcasting

---

wurst/objects/items/Items.wurst

$changelog: Fixed bug where Panic would lose its effect upon item usage.
This replaces #602 after force push was used to realign the 3.7e release.

Fixed bug where Panic would lose its effect upon item usage.

---

wurst/systems/commands/Skins.wurst

This change affects a single player and is therefore omitted from the changelog.
This replaces #604 after force push was used to realign the 3.7e release.

Fixed typo in BattleTag string constants.

---

wurst/objects/abilities/mage/hypnotist/DreamEater.wurst

$changelog: Fixed bug where Dream Eater would enter cooldown when cast on an invalid target.
The change stemmed from which event the order was aborted during. It needs to happen during `EVENT_PLAYER_UNIT_SPELL_CAST`, not `EVENT_PLAYER_UNIT_SPELL_EFFECT`. Both `EventListener.onTargetCast` and `registerSpellEvent` are based on the latter.

Reverted incorrect Dream Eater logic in order to properly cancel casting.

---

wurst/systems/boards/PlayerScore.wurst
wurst/systems/boards/ScoreBoard.wurst

After recent scoring implementation changes, scores being recorded would cause a null pointer exception because `playerScores.get([tribe player])` would return `null` and then fail to record the value.
This is fixed by adding the tribe player to the `playerScores` mapping. However, this causes double counts because the API for recording values will automatically call the associated API for recording the same value for the tribe player. In order to avoid this for now, the second API call will short-circuit if the original player is the tribe player. In the long run, we should disassociate the scoreboard API entirely from the tribe concept.
Although adding the tribe player to the mapping should prevent null pointer exception, checks have also been added to make sure that the mapping had a …

Corrected scoring logic for tribe player.

---

wurst/objects/items/Raw.wurst

$changelog: Fixed bug where Medallion of the Thief was not usable.
The old ability was accidentally deleted when cleaning up legacy object definitions [here](https://github.com/island-troll-tribes/island-troll-tribes/commit/9642ce3bb2c7b86ae939ee4724c4f001a45866b7#diff-44e570ae16a7f44a386fa54403d8ce856804999f8fb20f0a54d6c5dad228c237L648-L662). Rather than reverting that deletion, the ability was switched to match the one used by Thief, `ABILITY_TELEPORT`. All of the relevant parameters are the same, except that the casting time is now 0 instead of 0.2, which also matches the original Blink in the base game.

Corrected ability ID for Blink in Medallion of the Thief.

---

wurst/systems/modes/ForcedDuel.wurst
wurst/systems/modes/GameConfig.wurst
wurst/systems/modes/GameModeInit.wurst
wurst/systems/modes/Respawn.wurst
wurst/systems/modes/ShrinkingMap.wurst

$changelog: Changed modes that set a timer, such as grace period and forced duel, to use seconds instead of minutes.
This gives more flexibility without having to resort to decimals, but still isn't ideal. Longterm, we probably want an `Interval` type of some sort that automatically interfaces between `real` and `int` and supports combing seconds and minutes, e.g. `"06:30".toInterval() == Interval(6.5) == Interval(390)`.

Changed duration inputs for modes to use seconds instead of minutes.

---

wurst/assets/LocalAssets.wurst
wurst/objects/abilities/MoveCorpses.wurst

I'll update this description if this change turns out to address desyncs. Using the `getPos3Real` may cause desyncs due to using `GetLocationZ`, but this is not yet confirmed. Keeping this change regardless because it's makes sense to use object fields over triggers when appropriate.

Used ability definition for sound effects when moving corpses.

---

wurst/systems/commands/Hints.wurst

$changelog: Fixed bug where players would desync depending on their setting for hints.
The desync was caused by encapsulating the whole block in a comparison against `localPlayer`, specifically because `HINT_SOUND.playForPlayer` changes instance fields, which are global variables.
Instead a loop is used so the same adjustment is made for everyone and then the lower level actions are responsible for checks against `localPlayer`, which ensures that only basic native calls are inside of `localPlayer` checks.

Corrected checks for local player when displaying hints.

---

wurst/systems/commands/Skins.wurst

Added back some missing entries now that I know the new BattleTag matching these usernames.
Changed the formatting to not use `vararg` inputs because require extra lines in the differential due to the lack of support for trailing commas. With one input per call to `register`, adding a new player to a skin just requires adding a line, without adding a comma to a different line.

Added back missing BattleTags to skins registry.

---

wurst/systems/boards/ScoreBoard.wurst

$changelog: Fixed scoreboard timer for observers.
When I rewrote scoreboard, I made it so it only update on event such as kill/item sold, but I forgot to periodically update the board timer.

Fixed scoreboard timer for observers.

---

wurst/objects/items/LivingClay.wurst

$changelog: Fixed bug that allowed Living Clay to damage a unit without exploding.
$changelog: Restricted the Paranoia aura to affect only units that can destroy Living Clay.
The abilities for dealing AoE damage and destroying the ward are separate. Having different target types allows the first to fire without the second. The targets for Paranoia were changed so that all abilities are synced.

Corrected mismatch in target types for the Living Clay abilities.

---

wurst/objects/units/TrollBuildings.wurst

$changelog: Reverted health for Mixing Pot, Workshop, and Witch Doctor's Hut from 250 to 260, 275, and 325, respectively .
$changelog: Reverted armor type for Mixing Pot and Workshop from Fortified to Heavy.
I've noticed those changes compared to 3.2 version, I believe this is an oversight from rewriting the troll buildings definition. Building HP should scale with their price.

Reverted health and armor type for some buildings.

---

wurst/objects/items/Items.wurst

$changelog: Increased the stock replenish interval on merchants from 60 to 120 seconds for crafted materials, including ingots, spirits, and poisons.
I forgot to set the stock replenish interval for the crafted materials definition when I rewrote them. I checked all current items replenish interval and compared them with the version 3.2, here's a list of current items stock interval :
-Most buildings kits had & have 30 seconds, magic seed being the exception with 180
-Scrolls had 180, they currently have 120
-Basic materials (stick, tinder, clay, flint) have & had 120
-Crafted materials had 120, they have 60 after 3.6b if my memory is correct.
-Shields & Axes had 180, they have 120 after 3.4a I believe, I set it to 120 when I rewrote them.
-Iron coat & boots had 60, they have 120, iron …

Increased stock replenish interval for crafted materials.

---

wurst/objects/units/Animals/ElkDefinition.wurst

$changelog: Fixed bug where a pet Elk would miss when attacking a fleeing target.
The attack range motion buffer for elk was set to 0 as the original unit is a critter and do not have an attack, I can't tell why it wasn't an issue with previous elk pet definition, maybe because it used to attack with missile and not melee.

Corrected attack range motion buffer for pet Elk.

---

wurst/objects/abilities/mage/hypnotist/DepressionAura.wurst

$changelog: Removed slowing effect from Depression Aura.
I've seen people voting (4 to 0) this change in the suggestion channel from the ITT discord, pretty sure nobody would disagree with this, everybody have been saying for month that elementalist & hypnotist are busted.

Removed slowing effect from Depression Aura.

---

wurst/objects/units/TrollUnitTextConstant.wurst

$changelog: Reverted base Scout ability to Radar instead of Ward the Area.
Current Ward the area is a starting ability for scout, it can place 1 ward lasting 480 seconds with a 70 seconds cooldown, this ability has replaced ping the enemy in #547 , the feedback from the player is mostly negative, issue being that this spell is quite useless as a lvl 1 spell compared to ping the enemy. 
It has a high cooldown for placing only 1 ward, in comparison, you can craft 6 ward with 2 clay & a mc from workshop which is clearly cheap, it makes this ability feels useless. 
At level 1, scout used to be able to accompany a hunter/bm to hunt more effectively using radar, this isn't possible with current ward ability which you can't use unless you... rush middle island to ward I guess? Well I find rare …

Reverted base Scout ability to Radar instead of Ward the Area.

---

wurst/objects/items/MageMasher.wurst

$changelog: Increased mana drain per hit on Mage Masher from 6 to 10.
With mage and priest having a mana pool of 350 mage masher feels like a butter knife. This will give it slightly more power. Longer term we may want to consider % drain.

Increased mana drain per hit on Mage Masher.

---

wurst/lib/OrderStringFactory_config.wurst
wurst/objects/abilities/priest/masterhealer/SelfPreservation.wurst
wurst/objects/abilities/scout/ScoutRadars.wurst
wurst/systems/crafting/QuickMakeSpell.wurst

$changelog: Fixed bug where Self-Preservation would not enter cooldown properly.
$changelog: Fixed bug where Restore Mana on Horn of the Mammoth would not activate properly.
Self preservation conflicted with quick make Witch doctors hut, horn of mana with quick make Omnitower Kit, we are bound to encounter more issue like this in the future as most channeled ability still rely on the orderId factory.

Fixed conflict for several order IDs.

---

wurst/systems/boards/ScoreBoard.wurst
wurst/systems/core/Tribe.wurst

$changelog: Fixed bug where the scoreboard would be displayed prematurely in games with many tribes.
I forgot to specify player in the scoreboard display method upon a tribe defeat, therefore it displayed the scoreboard for every one when 1 tribe was defeated.
Also fixed the square icon next to the tribe name which now turns red when a tribe is defeated.

Fixed bug where scoreboard displayed prematurely in 3+ team games.

---

wurst/objects/items/Workshop/BlowgunDefinition.wurst

$changelog: Increased cooldown on Blowgun from 6 to 9 seconds for all types of ammunition.
$changelog: Decreased damage per tick for Thistle in Blowgun from 5 to 1.
I am having trouble reaching a solution regarding blowgun from first boat, in the end, you can just buy workshop & the material from first boat, doesn't seem like it would really solve the issue that blow gun is too strong, so I decided to nerf the numbers.
Thistles damage can deal 15 instant damage + 5 x 5 decaying damage over 16 seconds, In 3.2 it dealt 20 instant damage & 1 decaying damage, reducing decaying damage to 1 would also avoid issue with XP being given to another player due to dummycast changing owner, even though you can fix this by not using InstantDummyCaster, I don't really want to spend time on this, maybe …

Nerfed Blowgun.

---

wurst/objects/units/units.wurst

$changelog: Changed armor type for Tent from Fortified to Light.
Tent having fortified doesn't make much sense, it's a tent built from hides, it should feel "squishy" and not hard as rock.

Weakened armor type for Tent.

---

wurst/objects/units/Merchants.wurst

$changelog: Replaced Blowgun with Tinder for the first set of merchant ships.

Replaced Blowgun with Tinder for the first set of merchant ships.

---

wurst/objects/abilities/beastMaster/UltimateForm/Devour.wurst

Jungle Tyrant Devour's tooltip wasn't precising that the target must be below 50 HP.

Updated tooltip for Devour.

---

wurst/systems/buildings/SpiritWard.wurst

$changelog: Reverted Spirit Ward to have unlimited uses.
Not sure why it was changed, but 1 ward per revive is too costly in pub games

Reverted Spirit Ward to have unlimited uses.

---

wurst/objects/abilities/mage/hypnotist/DreamEater.wurst

$changelog: Fixed bug where Dream Eater could not be cast on a valid target.

Fixed check on target for Dream Eater.

---

wurst/objects/abilities/Omnicure.wurst
wurst/objects/abilities/beastMaster/Pets/PetGrowth.wurst
wurst/objects/abilities/beastMaster/Pets/PetReleasing.wurst
wurst/objects/abilities/beastMaster/Pets/PetSleep.wurst
wurst/objects/abilities/beastMaster/UltimateForm/Devour.wurst
wurst/objects/abilities/beastMaster/UltimateForm/ElkJump.wurst
wurst/objects/abilities/gatherer/NewItemWarp.wurst
wurst/objects/abilities/hunter/tracker/Beacon.wurst
wurst/objects/abilities/hunter/tracker/Sniff.wurst
wurst/objects/abilities/mage/dementia/ActivateRunesNew.wurst
wurst/objects/abilities/mage/dementia/DarkGateNew.wurst
wurst/objects/abilities/mage/dementia/DementiaRunesNew.wurst
wurst/objects/abilities/mage/elementalist/Brambles.wurst
wurst/objects/abilities/mage/elementalist/EarthGuardian.wurst
wurst/objects/abilities/mage/elementalist/FrostBlast.wurst
wurst/objects/abilities/mage/elementalist/Meditate.wurst
wurst/objects/abilities/mage/hypnotist/DepressionOrb.wurst
wurst/objects/abilities/mage/hypnotist/Seizures.wurst
wurst/objects/abilities/mage/hypnotist/StupefyField.wurst
wurst/objects/abilities/mage/unsub/ReduceFood.wurst
wurst/objects/abilities/priest/booster/AngelicElemental.wurst
wurst/objects/abilities/priest/sage/MaximumFervor.wurst
wurst/objects/abilities/priest/unsub/AntiMagic.wurst
wurst/objects/abilities/scout/Reveal.wurst
wurst/objects/abilities/scout/ScoutRadars.wurst
wurst/objects/abilities/scout/Trap.wurst
wurst/objects/abilities/scout/WardArea.wurst

I set the base order Id for all channel ability preset that were still relying on the automatic orderId attribution from the ChannelAbilityPreset class.
The issue was that the automatic setting could result in a conflict between spells and those would not cast properly.

Froze order IDs for abilities based on Channel.

---

wurst/systems/entities/bosses/TheOne.wurst

$changelog: Removed items drops received for killing The One.
Leaving this open for a bit while it is discussed.

Removed items drops received for killing The One.

---

wurst/objects/abilities/scout/Trap.wurst

$changelog: Fixed bug where a Tracking Trap could fail to cast Track on its target.
This also fixes the order ID conflict that was introduced in #668, which was never released.

Fixed Trapper abilities.

---

wurst/config/OrderStringFactory_config.wurst

We're no longer using the order string factory and this doesn't help much even if we were.

Removed spammy print at compiletime.

---

wurst/systems/commands/Commands.wurst

Ending the game mode selection when the player from the first slot type -obs, this way people don't have to wait when the player picking mode goes observer.

Updated -obs command to end mode selection when appropriate.

---

wurst/utils/ManaBurn.wurst

$changelog: Fixed bug where players could see mana burn text on targets without line of sight.

Fixed visibility for text tag for Mana Burn.

---

wurst/objects/abilities/BaseMapAbilities.wurst

$changelog: Reduced movement speed reduction for Snake poison from 35% to 20%.
$changelog: Reduced duration for non-heroes for Snake poison from 300 to 150 seconds.
Snake poison is too annoying, 2min is way too long, I don't understand the purpose of this duration, I reduced it to 30 seconds so if you get attacked by a snake when you are escaping/fighting with other troll, it still feels like it has an impact.

Reduced snake poison effects.

---

wurst/objects/items/Armory/SpearsDefinition.wurst

Although this import is not used, unrelated hash maps appear to break without it, but only in games with multiple players. In my test, I specifically saw the hash map in `Skins` break, where a retrieved skins for a unit was not null but also not a valid object.
This was broken in #701 and this is a revert of that change.

Fixing breaking import.

---

wurst/systems/core/Experience.wurst

$changelog: Fixed bug where trolls would stay alive at 0 energy.
MasterHealer brillance aura regenerate 0.33 mana per second, but the regeneration actually happen every ANIMATION_PERIOD (0.03), mana is a real value, I ran a test, did -mp 0 on MasterHealer but he still had 0.007 mana upon this check due to brillance aura regeneration, therefore he doesn't die with 0 mana being displayed in the portrait. 
I changed this check 10 month ago, I don't remember why, it used to do a proper check.

Fixed decimal rounding when checking death due to energy.

---

wurst/objects/units/Buildings/Huts.wurst

Dropped when merging #585 after being added in #657. Not going to include this in the changelog again as it was a minor bug that only briefly reappeared.

Restored model fix for Mud Hut.

---

wurst/assets/LocalObjectIDs.wurst
wurst/objects/items/CloaksDefinition.wurst

$changelog: Fixed bug where Cloaks would not grant +3 to all stats.
Mistake from #585 
Recently updated wurststdlib2 to include the all stats +3 ability in the AbilityIds package.

Fixed All +3 ability on Cloaks.

---

wurst/extensions/UnitExtensions.wurst
wurst/objects/abilities/Heat.wurst

$changelog: Fixed bug where Bonfire failed to heat nearby units.
This is caused by the `TargetsAllowed.player_t`, which restricts targets to the units of the same player as the caster. There isn't a need to restrict the targets much, as the buff is only checked for trolls in `StatLoss` anyway. Filtering for targets is only useful for avoiding confusing players by showing the buff on irrelevant units.

Fixed bug where Bonfire failed to heat nearby units.

---

wurst/objects/units/Buildings/NeutralBuildings.wurst

A quick fix to avoid this error in case you want to work on something else, don't know how it should properly be fixed.
Stdlib added a `commaList(LinkedList<int> ids)` which conflict with the `commaList(vararg LinkedList<int> lists)` defined [here](https://github.com/island-troll-tribes/island-troll-tribes/blob/d792e4dbef25df39a6512957058e604bcf687f1d/wurst/utils/ObjEditingUtils.wurst#L9)

Quickfix to avoid error from commaList ambigeous definition

---

wurst/objects/abilities/scout/Reveal.wurst

$changelog: Increased radius for Reveal slightly: for level 1 from 1000 to 1200, for level 2 from 1700 to 1800.
Scout level 1 reveal is deemed as useless as the radius is too low
Previous radius : 300 + 700, 300 + 700 * 2, 300 + 700 * 3
I increased starting radius and reduced radius per level to not affect level 3 radius as it is already pretty big
Current radius ; 600 + 600, 600 + 600 * 2, 600 + 600 * 3

Buffed scout lvl 1 & 2 reveal radius

---

wurst/objects/items/Armory/ShieldsDefinition.wurst

$changelog: Prevented Shield Bash from targeting bosses.
Bashing boss would make them wander around, sometimes getting out of the mid-boss pit, preventing them from attacking for like 7-8 seconds, effectively saving a lot of meat for the attacker, that doesn't healthy at all, it's supposed to be a boss fight.
It sounds silly in the first place to be able to bash such huge monster with a shield.

Prevented Shield Bash from targeting bosses.

---

wurst/objects/abilities/hunter/Track.wurst

$changelog: Improved the armor reduction for Greater Track armor from 4 to 5; duration, from 30 to 25 seconds; cooldown, from 50 to 35 seconds.
Tracker feels underwhelming, the tooltip for greater track was incomplete, buffed greater track a bit to incite people to play tracker.
Refactored code a bit as it was unintuitive.

Improved duration, cooldown, and armor reduction for Greater Track.

---

wurst.build

It's easier to notice the lobby when the map name is colored in the lobby list, filtering the map name also brings up the downloaded map upward the list.

Changed text color for the map name to gold.

---

wurst/objects/abilities/BossAbilities.wurst
wurst/objects/units/Bosses/MidBossDefinition.wurst
wurst/systems/entities/modules/Hostile.wurst

$changelog: Added 30% Spell Resistance to Mammoth & Disco Duck.
This change has been requested for a while as it seems too easy for mage class to deal damage on mid-bosses.
I reused the MagicResistance.wurst code made by @HallerJohn to save time & to increase the codebase.
Should replace the "magic resistance" terminology by "spell resistance", magic implies that magic damage from bees are reduced, while it is not the case, only reduce damage from spells, it uses the runed brace item ability.

Added spell resistance to Mammoth and Disco Duck.

---

wurst/objects/items/Armory/SpearsDefinition.wurst
wurst/objects/items/Spears.wurst
wurst/systems/crafting/QuickMakeToolTips.wurst

$changelog: Updated Dark Spear mana drain from 30% of current mana to 10 plus 40% of current mana.
Dark spear had been nerfed in #496 to the point where it was nearly useless to answer "aggressive" nerf suggestions.
It has been a year now and community has asked for a buff.
Made this change following discussion from the discord.

Buffed mana drain on Dark Spear.

---

scripts/release.py

We added a color for the map name in #773, I didn't notice that the release script used the map name defined in the wurst build file to create a string for the filename, color code on filename crashes the wurst build script.

Fixed error when building map

---

wurst/objects/abilities/beastmaster/Druid/BarkSkin.wurst

$changelog: Fixed bug where two units with Barkskin fighting would cause the game to crash.
If 1 unit with barkskin buff attacks another unit with the same buff, reflected damage would trigger the buff damage in an infinite loop fashion.
Apparently just putting `ATTACK_TYPE_CHAOS` is enough to inflict pure damage.

Fixed infinite loop caused by Barkskin reflecting.
