src/trolls/gatherer/Item Warp.j

Changes:
-Now scales properly with level (900 * level).
-Speed of items being pulled increased (speed 10 -> 15).

Update Item Warp.j

---

src/trolls/scout/Enemy Radar Uber.j
src/trolls/scout/Enemy Radar.j

-Changed ping style for elks from 'flashy' to 'simple'. (! to point)
-Lightened ping color to increase visibility.

Enemy Radar elk ping update

---

src/systems/crafting/Mixing Pot Stuff.j

Changed Ele Shield pot, Reduced # of stems to >0 and changed river root to butsu>0

Update Mixing Pot Stuff.j

---

src/trolls/gatherer/Item Radar.j
src/trolls/gatherer/Radar Skill 1.j
src/trolls/gatherer/Radar Skill 2.j
src/trolls/gatherer/Radar Skill 3.j
src/trolls/gatherer/Radar Skill 4.j
src/trolls/gatherer/Radar Skill 5.j
src/trolls/gatherer/Radar Skill 6.j

-Gatherer's Item Radar ping style changed to simple. (Was flashy)

v2103 Item radar ping

---

src/lib/PublicLibrary.j
src/systems/crafting/Mixing Pot Stuff.j
src/systems/crafting/Transmute.j
src/trolls/mage/Metronome.j

-Moved Bee Hive recipe from Workshop to Mixing Pot (recipe now SpecHerb + 2 River Stem). Creates 2 Bee Hives per batch. Still need to remove recipe from recipe ward.
-Metronome waits longer between spells (0.5 -> 1.0) and casts fewer spells (9 -> 5). Cyclone removed from spell list.
-Medallions of Courage may drop more than once per game. Swapped Dark Spears with Steel Ingots in medallion loottable. Drop chances are now 7:1 medallion:ingot.
Sorry about the excess whitespace changes, not sure what Atom is doing there.

v2103b Beehive / Metronome / Medallions

---

src/lib/PublicLibrary.j
src/systems/Meat And Bone.j

-Beastmaster's increased chance of getting pets no longer requires getting the last hit, just close proximity. (400 range)

v2103e Beastmaster doesn't require lasthit

---

jass/systems/Meat And Bone.j

Fixed panthers and snakes leaking meat.

Update Meat And Bone.j

---

wurst/lib/InventoryEvent.wurst
wurst/lib/ItemRecipe.wurst
wurst/lib/ItemRestriction.wurst
wurst/lib/SmoothItemPickup.wurst
wurst/lib/StackNSplit.wurst
wurst_run.args

Listed packages are added to replace existing ITT item handling.
Further patches will introduce usage of new and removal of obsolete
code.
- InventoryEvent, for intuivite inventory event handling
- ItemRecipe, powerful item recipe creator
- ItemRestriction, for restricting or limiting items from being equipped
- SmoothItemPickup, allows for item pickup during certain conditions
even when unit inventory is full
- StackNSplit, easy item charges stacking and splitting

Addition of new item-related packages.

---

wurst/lib/ItemRecipes.wurst

Following have been included in this patch:
- troll recipes
- armory recipes
- workshop recipes
- witch doctor hut recipes
- tannery recipes
- mixing pot recipes
Initialization block is not included i.e. no recipe initialization is
actually invoked - it will be a part of patch responsible for removal
of old, deprecated item recipes.

Declaration of item recipes.

---

wurst/utils/Analysis.wurst

Analysis.wurst contains tools for calculating rect land areas and water areas, together with item spawn chance variables these can allow calculating item densities for item spawning.
Init function is commented out, this is meant as a developing tool only and has no impact on the game.

Rect analysis tools for balancing the game

---

wurst/__legacy__/spawns/Spawns.jurst

https://github.com/island-troll-tribes/island-troll-tribes/issues/115
There was a flag udg_more_baddies that wasnt set or used anywhere. Removed requirement for said flag

Simplified logic for -rb mode

---

wurst/systems/units/hostiles/AlligatorMan.wurst
wurst/systems/units/hostiles/AncientHydra.wurst
wurst/systems/units/hostiles/BonyAnimal.wurst
wurst/systems/units/hostiles/DiscoDuck.wurst
wurst/systems/units/hostiles/Hawk.wurst
wurst/systems/units/hostiles/Hostile.wurst
wurst/systems/units/hostiles/LesserHydra.wurst
wurst/systems/units/hostiles/Mammoth.wurst
wurst/systems/units/hostiles/Panther.wurst
wurst/systems/units/hostiles/RearingAnimal.wurst
wurst/systems/units/hostiles/Snake.wurst
wurst/systems/units/hostiles/TheOne.wurst

UnitEntities now generate drops list on death instead of on creation

UnitEntity optimization

---

wurst/systems/units/hostiles/trolls/ElementalistOld.wurst

Added unitentity for new elementalists type ID as well

Added UnitEntity for new Elementalist

---

wurst/__legacy__/lib/ITTAbilityIds.wurst
wurst/systems/units/hostiles/BabyAnimal.wurst
wurst/systems/units/hostiles/BearCub.wurst
wurst/systems/units/hostiles/Fawn.wurst
wurst/systems/units/hostiles/WolfPup.wurst

Baby animals move slightly on spawn so they wont interfere with item pickups

Changed baby animals to move off of drops upon spawn

---

wurst/systems/tutorials/RecipeIslandDemo.wurst

Removes any possible fawns spawned in recipe island tutorial/demo

Fixed removal of fawn at the end of the recipe island demo

---

wurst/systems/spells/PreventNet.wurst

Removed AMS block versus Workshop nets

---

wurst/systems/core/ItemAmount.wurst

Appends "(x itm.getCharges())" on items when dropped, and removes the suffix on pickup

Show item charges while on ground

---

wurst/_items/Blowgun.wurst

Attack speed slow factor 0.3 -> 0.15
MS slow factor 0.4 -> 0.3
Duration 7.5s -> 6.5s

Nerfed regular thistles' effect versus heroes.

---

wurst/systems/commands/Commands.wurst
wurst/systems/commands/Hints.wurst
wurst/systems/modes/Quests.wurst
wurst/systems/spells/mage/elementalist/Brambles.wurst

Just saw another player struggling for crafting stuff, added some hint and a command in case they don't read the quest log.

Updated Hint,Quest Log, added a "-crafting" command

---

wurst/systems/commands/GoldTrading.wurst

I had a game where my teammate passed his gold to a leaver. Just added an if check.

Prevent gold trading with leaver

---

wurst/systems/spells/gatherer/Radars.wurst

I published this on upstream by mistake instead of my forked repo, dunno if it's a big deal

Wrapped up the gatherer radar package, formatted it a bit so it's easier to read

---

wurst/extensions/UnitExtensions.wurst
wurst/systems/crafting/QuickMakeSpell.wurst
wurst/utils/AbilityObjectCreationUtils.wurst

I might use this to create some spellbook, nothing to add right now

SpellBookObject class to create spellbook

---

.circleci/config.yml

Yoyo, setup cli has changed again.
I also started rolling out a docker image which will be the next step for easier building.

Fix circle CI build

---

.circleci/config.yml

Much cleaner, and also faster now 📦

Use docker-wurst image for CI

---

wurst/systems/core/Tribe.wurst
wurst/systems/modes/TribeOwnsBuildings.wurst

Fix bug caused by -tg when buildings buy from trade ships

---

wurst/__legacy__/lib/ID.jurst
wurst/_units/Animals/ElkDefinition.wurst
wurst/_units/Animals/FishDefinition.wurst
wurst/_units/Animals/FlyingUnitDefinition.wurst
wurst/_units/Animals/JungleBearDefinition.wurst
wurst/_units/Animals/JungleWolfDefinition.wurst
wurst/_units/Animals/PantherDefinition.wurst
wurst/_units/Animals/SnakeDefinition.wurst

Not interesting, but it should be easier to update those later on

Wrote UnitDefinition for animals

---

wurst/_items/Kits/ForgeKit.wurst
wurst/_units/TrollUnitTextConstant.wurst
wurst/objects/units/Merchants.wurst
wurst/systems/spells/mage/elementalist/Brambles.wurst

@changelog: Forge Kit cost increase from 15 to 20.
@changelog: Workshop Kit on boat 3 and 4 replaced with Armory Kit.
@changelog: Fixed bug with Troll item slot tooltip.
@changelog: Temporarily increased loop interval on Brambles to reduce lag.

Bug fixes and boat adjustments

---

wurst/systems/boards/TribeBoard.wurst

*Fix bug with scoreboard caused by obs leaving game.

Fixed multiboard bug caused by an observer leaving.

---

wurst/objects/units.wurst

$changelog: Fixed bug where omnidefender did not have proper pathing.

Fixed pathing for omnidefender.

---

wurst/systems/spells/scout/Trap.wurst

$changelog: Fixed bug where trapper could not create traps.

Fixed base unit ID for traps.

---

wurst/systems/crafting/QuickMakeSpell.wurst
wurst/systems/spells/TrollUpgrade.wurst
wurst/systems/spells/beastMaster/Shapeshift.wurst

$changelog: Fixed bug where Shapeshifter abilities such as Wolf's Hunger would reset cooldown when shapeshifting.

Fixed bugs related to abilities transitioning during transformations.

---

wurst/systems/spawns/ResourceSpawns.wurst
wurst/systems/spells/beastMaster/Pets/PetGrowth.wurst

$changelog: Fixed bug causing tamed pets to grow instantly.
$changelog: Fixed bug with green fish spawn rates.

Fixed bugs introduced in v3.4e.

---

wurst/objects/units/TrollBuildings.wurst
wurst/systems/modes/GameModeInit.wurst

Corrected names of Forge and Workshop.
Removed -om from -to.

Minor bugfixes.

---

wurst/lib/OrderStringFactory_config.wurst
wurst/lib/commands/ModifySelected.wurst
wurst/objects/abilities/Magic.wurst
wurst/objects/abilities/priest/unsub/CureAll.wurst

$changelog: Fixed bug where issuing an order would sometimes use the wrong ability.
Also adds more features to the toolkit.

Corrected conflicting order IDs.

---

wurst/assets/IdListConstant.wurst

$changelog: Fixed bug where spear was used instead of stick in some recipes.

Fixed incorrect item ID reference

---

wurst/__legacy__/crafting/Transmute.jurst

$changelog: Fixed bug where the Iron Shield recipe was incorrect.

Fixed typo in recipe for Iron Shield.

---

wurst/systems/commands/Hints.wurst

I set hint interval to 5 second for debug, forgot to revert it.

Reverted hint interval from debugging value.

---

wurst/objects/abilities/MoveCorpses.wurst

Now it should behave as a 3D sound.

Corrected sound for grabbing / dropping corpses to be 3D.

---

wurst/lib/OrderStringFactory_config.wurst
wurst/lib/Transformation.wurst
wurst/lib/commands/Alliances.wurst
wurst/lib/commands/MonitorOrders.wurst
wurst/objects/abilities/gatherer/Radars.wurst
wurst/objects/abilities/mage/unsub/ReduceFood.wurst
wurst/objects/abilities/priest/sage/LightGateNew.wurst
wurst/objects/abilities/priest/unsub/AntiMagic.wurst
wurst/objects/abilities/priest/unsub/HealingWave.wurst
wurst/objects/abilities/priest/unsub/MixSpells.wurst
wurst/objects/abilities/priest/unsub/RangedHeal.wurst
wurst/objects/abilities/thief/contortionist/NewSmokeStream.wurst
wurst/objects/abilities/thief/escapeArtist/Jump.wurst
wurst/systems/crafting/QuickMakeSpell.wurst

$changelog: Fixed bug where some abilities could have an effect without finishing casting.

Updated channel abilities to use generated orders.

---

wurst/objects/abilities/Sleep.wurst

$changelog: Reduced heat loss when sleeping outside from 20 to 15.

Reduced heat loss when sleeping outside.

---

wurst/systems/core/Tribe.wurst

$changelog: Added a message to inform players that a tribe has been defeated.

Added a message to inform players that a tribe has been defeated.

---

wurst/__legacy__/crafting/Transmute.jurst
wurst/systems/crafting/QuickMakeToolTips.wurst

Removed recipes for Battle Gear that were left in the workshop.
Updated tooltips for Living Clay and Dark Spear.

Fixed miscellaneous recipe problems.

---

wurst/objects/items/ScrollsDefinition.wurst
wurst/systems/crafting/QuickMakeToolTips.wurst

Updated the quick make tooltip for scrolls.
Hunting net & cloak tooltip adjusted so it feels consistent (mostly color fix)
Changed a few string color for material because it wasn't really visible (blue was too dark)

Updated quickmake tooltips.

---

wurst/systems/core/ReduceHealing.wurst

$changelog: Fixed bug where the healing tracker would display an incorrect number.

Fixed clean up for healing reduction on unit death.

---

wurst/__legacy__/crafting/Transmute.jurst

$changelog: Fixed bug preventing Iron Shield from being crafted.

Fixed Iron Shield recipe.

---

wurst/systems/core/ReduceHealing.wurst

Including the changelog message I missed in the squash commit for #540 in this one.

Fixed testing value for healing reduction duration.

---

wurst/objects/items/MixingPot/Cure.wurst
wurst/objects/items/Raw.wurst
wurst/systems/crafting/Mixing.wurst
wurst/systems/crafting/MixingPotQuickMake.wurst
wurst/systems/crafting/QuickMakeToolTips.wurst

$changelog: Lowered price of Cure All from 12 to 8 gold per 2 charges.
$changelog: Lowered price of Spirit of Darkness from 25 to 12 gold.
$changelog: Changed Cure All recipe from 2 to 3 Athelas Seeds.
Last year I changed cure all recipe from 3 to 2 athelas seed, as I didn't see it being mentioned in the changelog, I believe I made a mistake, Liquid is still mix 3 athelas to get cure all.
Recently I've spotted people mass producing cure all or orb of darkness just to sell it, orb sells for 16 gold when it only require 1 stem 1 root 2 athelas, 6 cure all would sell for 23 gold, basically 6 athelas == steel ingot, I don't think that's good design.

Updated Cure All and Spirit of Darkness.

---

wurst/objects/abilities/beastMaster/Pets/PetRevive.wurst

Improved UI elements for pet reincarnation.

---

wurst/systems/core/ClassSelector.wurst
wurst/systems/modes/GameConfig.wurst
wurst/systems/modes/GameModeInit.wurst

$changelog: Added -start-level mode, which increases the starting level for trolls.
I didn't adjust spawning rate with this mode, thought that people might just add -fast too.

Added starting level mode.

---

wurst/assets/LocalObjectIDs.wurst

I messed up my merging on #581 and deleted a few used ability Ids by mistake.

Reverted part of #581.

---

wurst/systems/commands/Skins.wurst

$changelog: Updated skins to unlock based on BattleTag instead of username.

Corrected skins to use BattleTag; removed incomplete listings.

---

wurst/systems/entities/bosses/Mammoth.wurst

$changelog: Fixed bug where central gate could be destroyed prematurely.

Fixed bug where central gate could be destroyed prematurely.

---

wurst/objects/items/Items.wurst

$changelog: Fixed bug where panic would loose its effect on item cast/consume

Fixed bug where panic would loose its effect on item cast/consume

---

scripts/release.py

This uses the experimental API for getting pulls associated with a commit. For a PR merged via squashing, there will be a one-to-one correspondence between PRs and commits, although it's not clear why the API supports multiple PRs for a single commit.
The iteration over commit history assumes that all PRs are merged via squash directly to master.

Updated release script to extract changelog from PRs instead of commits.

---

wurst/systems/modes/GameConfig.wurst
wurst/systems/modes/GameModeInit.wurst
wurst/systems/modes/Respawn.wurst

$changelog: Added mode for configuring when the central gate is opened.

Added mode for configuring when the central gate is opened.

---

wurst/systems/ui/Status.wurst

$changelog: Changed the UI to display effects on units more prominently.
Preview:

Changed the UI for the status bar.

---

wurst/objects/units/units.wurst

$changelog: Reduced health for Tent from 160 to 100.
Tent is pretty cheap, I believe its hp should be adjusted in relation to its cost.

Reduced health for Tent.

---

wurst/assets/LocalObjectIDs.wurst
wurst/systems/crafting/QuickMakeSpell.wurst
wurst/utils/AbilityObjectCreationUtils.wurst

I don't think this needs a changelog, as most players who read the changelog are already aware of the teleporter beacon recipe.

Added back quickmake for Teleporter.

---

wurst/systems/modes/Respawn.wurst

$changelog: Added invulnerability to the Mammoth while the gate is closed.

Added invulnerability to the Mammoth while the gate is closed.

---

wurst/systems/entities/animals/Bear.wurst

$changelog: Removed bear cub pending balance changes for pets.

Removed bear cub pending balance changes for pets.

---

wurst/objects/items/Kits/TrollBuildingKits.wurst

$changelog: Reverted number of charges for Magic Seed to 2.

Reverted number of charges for Magic Seed to 2.

---

wurst/objects/abilities/HostileAnimalAbilities.wurst

Should have been fixed in #585.

Added back dropped change.

---

wurst/assets/LocalObjectIDs.wurst
wurst/objects/abilities/SelectAbilities.wurst
wurst/objects/units/Buildings/Fire.wurst
wurst/objects/units/Buildings/NeutralBuildings.wurst

Should have been merged with #585, I forgot about it.

Fixed Neutral Building ability.

---

wurst/objects/abilities/Sleep.wurst

Another mistake from #585 I didn't see.

Fixed hotkey for sleep.

---

wurst/systems/cosmetics/LeagueSkins.wurst

No changelog because he'll see the message in game anyway.

Enabled lasvegass for his old skins.

---

wurst/systems/settings/SharedGold.wurst

$changelog: Fixed bug where simultaneous transactions could desynchronize shared gold.

Fixed desynchronization of shared gold pools.

---

wurst/objects/abilities/hunter/tracker/Sniff.wurst
wurst/systems/entities/modules/Hostile.wurst

$changelog: Fixed bug where Sniff would locate targets incorrectly.

Corrected unit targeting for Sniff.

---

wurst/lib/DamageTags.wurst

Accidentally forgot to add this in #747

Added missing file for damage library.

---

wurst/systems/core/ClassSelector.wurst
wurst/systems/modes/GameConfig.wurst
wurst/systems/modes/GameModeInit.wurst

$changelog: Added the -ban mode allowing the host to ban a single class.

Added -ban mode.

---

wurst/lib/HealingSystem.wurst
wurst/objects/items/CloaksDefinition.wurst

$changelog: Increased regeneration interval of cloaks from 5 to 15 seconds.
$changelog: Prevent multiple castings of Cloak of Healing from stacking.

Nerfed stacking of Cloaks of Healing.

---

wurst/objects/items/Armory/SpearsDefinition.wurst
wurst/objects/items/Materials/BasicMaterials.wurst
wurst/objects/items/Spears.wurst

$changelog: Changed spears to recover if and only if the target immediately dies.

Reworked spear recovery.

---

wurst/objects/items/Spears.wurst

$changelog: Removed spear recovery.

Removed spear recovery.
